export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const SET_USER_AUTH_DATA = "SET_USER_AUTH_DATA";
export const SET_CANVAS_LIST = "SET_CANVAS_LIST";

export const SET_CANVAS_ACTION_TYPE = "SET_CANVAS_ACTION_TYPE";